baseURL = 'https://guillaumebabik.github.io/'
languageCode = 'fr-FR'
title = 'LMR Consulting'
theme = 'adritian-free-hugo-theme'

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "A propos de moi"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Services"
  URL = "#services"
  weight = 3

  [[menu.header]]
  name = "Références"
  URL = "#portfolio"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 25

  [[menu.footer]]
  name = "A propos de moi"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Services"
  URL = "#services"
  weight = 3

  [[menu.footer]]
  name = "Références"
  URL = "#portfolio"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "services", "client-and-work", "contact"]

  homepageExperienceCount = 5

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false
  
  [params.logo]
    text1 = "LMR"
    text2 = "Consulting"

  [params.footer]
      copyright = "© LMR Consulting. All Rights Reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
